# Generated by Django 3.2.19 on 2023-07-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_informacionpersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpersonal',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='pais',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='profesion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
